In [1]:
# Import libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
pd.set_option('display.max_colwidth', 100)

from statsmodels.tsa.stattools import grangercausalitytests

# Import Twitter Sentiment Data

In [3]:
path_twitter_sentiment = '../../../../data/team/NLTK Time Series/sentiment_nltk_fixed_final.csv'

In [4]:
twitter_sentiment = pd.read_csv(path_twitter_sentiment)
twitter_sentiment.drop('Unnamed: 0', axis=1, inplace=True)
twitter_sentiment['Date'] = pd.to_datetime(twitter_sentiment['CreatedAt'].str[:10], errors='coerce')
twitter_sentiment.set_index('Date',inplace=True);
twitter_sentiment.drop('CreatedAt', axis=1, inplace=True)

In [9]:
twitter_sentiment

,company,TweetText,Tweet_lemmatized,neg,neu,pos,compound
Date,,,,,,,
2021-04-01,first_solar,First Solar Completes Sale of North American O&amp;M Business to NovaSource $FSLR https://t.co/j...,"['first', 'solar', 'completes', 'sale', 'north', 'american', 'oampm', 'business', 'novasource', ...",0.000,0.000,0.000,0.0000
2021-03-31,first_solar,$ALYI To Reveal New Significant Investment In Company From Leading Texas Based Private Equity Fu...,"['alyi', 'reveal', 'new', 'significant', 'investment', 'company', 'leading', 'texas', 'based', '...",0.000,1.000,0.000,0.0000
2021-03-31,first_solar,@SolarPowerEU @renewableH2EU @EU_Commission @Akuo_Energy @enelgreenpower @EdpRenewables @Enapter...,"['solarpowereu', 'renewableheu', 'eucommission', 'akuoenergy', 'enelgreenpower', 'edprenewables'...",0.000,0.927,0.073,0.2023
2021-03-31,first_solar,$FSLR sector move confirmed https://t.co/h08Dwn5CIF,"['fslr', 'sector', 'move', 'confirmed', 'httpstcohdwncif']",0.081,0.848,0.071,-0.0754
2021-03-31,first_solar,$FSLR NovaSource Power Services is World's Largest Solar O&amp;M Provider with Acquisition of Fi...,"['fslr', 'novasource', 'power', 'service', 'world', 'largest', 'solar', 'oampm', 'provider', 'ac...",0.000,1.000,0.000,0.0000
...,...,...,...,...,...,...,...
2011-01-10,meridian_energy,Panic Attacks Cure: Anxiety And Panic Attacks Cure - Energy Healing - Meridian Energy Therapy - ...,"['panic', 'attack', 'cure', 'anxiety', 'panic', 'attack', 'cure', 'energy', 'healing', 'meridian...",0.537,0.222,0.241,-0.8402
2011-01-07,meridian_energy,Just had some Meridian Energy guys come around saying they could save me a lot money. Said I was...,"['meridian', 'energy', 'guy', 'come', 'around', 'saying', 'could', 'save', 'lot', 'money', 'said...",0.537,0.222,0.241,-0.8402
2011-01-06,meridian_energy,EFT Cafe - Gratitude Tapping: AAMET - Association for the Advancement of Meridian Energy Techniq...,"['eft', 'cafe', 'gratitude', 'tapping', 'aamet', 'association', 'advancement', 'meridian', 'ener...",0.122,0.609,0.269,0.4393
2011-01-02,meridian_energy,Anxiety and Panic Attacks Cure - Energy Healing - Meridian Energy Therapy - Quantum Solutions ht...,"['anxiety', 'panic', 'attack', 'cure', 'energy', 'healing', 'meridian', 'energy', 'therapy', 'qu...",0.000,0.649,0.351,0.6597
NaT,NaN,NaN,NaN,0.413,0.255,0.332,-0.3818

In [7]:
twitter_sentiment_daily = twitter_sentiment.groupby(['Date']).mean()

In [8]:
twitter_sentiment_daily

                 neg       neu       pos  compound
Date
2011-01-01  0.006700  0.908400  0.084900  0.133425
2011-01-02  0.013154  0.709000  0.277846  0.482962
2011-01-03  0.014765  0.799088  0.186147  0.283909
2011-01-04  0.029500  0.772545  0.197955  0.271441
2011-01-05  0.000000  0.837762  0.162238  0.296990
...              ...       ...       ...       ...
2021-03-28  0.057020  0.785038  0.157945  0.213032
2021-03-29  0.057377  0.797468  0.145151  0.185867
2021-03-30  0.049820  0.792677  0.157501  0.213929
2021-03-31  0.056327  0.791030  0.152643  0.211125
2021-04-01  0.030713  0.819483  0.146743  0.235765

[3743 rows x 4 columns]

In [10]:
twitter_sentiment_daily.to_csv('twitter_sentiment_daily_all.csv')