In [2]:
import numpy as np
import pandas as pd
%matplotlib inline

# Data Cleaning

In [3]:
stock_prices = pd.read_csv('../../data/team/Stock Price Time Series/stock_prices_time_series_converged.csv')

In [5]:
stock_prices.drop(columns=['Unnamed: 9','Unnamed: 10'], inplace=True)

In [10]:
stock_prices.drop(columns=['mean delta', '-0.073169045'], inplace=True)

# Index datetime

In [12]:
stock_prices

      Ticker timestamp   open    high    low  close   volume  delta  deltaNorm
0       SPWR   4/23/21  28.07  29.420  27.51  29.01  3461071   0.94   0.243455
1       SPWR   4/22/21  27.92  28.980  27.40  27.66  4502055  -0.26  -0.044894
2       SPWR   4/21/21  25.60  27.410  25.02  27.38  2589691   1.78   0.445300
3       SPWR   4/20/21  26.50  26.898  25.17  25.93  3248555  -0.57  -0.119384
4       SPWR   4/19/21  27.45  28.220  26.07  26.54  3803556  -0.91  -0.201083
...      ...       ...    ...     ...    ...    ...      ...    ...        ...
32000  VWDRY   7/19/07  24.00  24.000  24.00  24.00     3763   0.00   0.017582
32001  VWDRY   7/18/07  23.25  23.450  23.25  23.25     8735   0.00   0.017582
32002  VWDRY   7/17/07  23.40  23.400  23.40  23.40     4464   0.00   0.017582
32003  VWDRY   7/16/07  23.55  23.550  23.55  23.55    10016   0.00   0.017582
32004  VWDRY   7/13/07  23.50  23.500  23.50  23.50     4679   0.00   0.017582

[32005 rows x 9 columns]

In [ ]:
stock_prices.index = pd.to_datetime(stock_prices['timestamp'])